config/routes.rb
Rails.application.routes.draw do

  resources :events do
  	member do
  		get 'start'
  		get 'stop'
  	end
  end
  resources :event_results, :only => [:edit, :update, :destroy] do
  	member do
  		get "start"
  		get "stop"
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "events#index"
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  occurrence     :string(255)
#  start_at       :datetime
#  job_name       :string(255)
#  job_arguments  :json
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  priority       :integer          default("10")
#  job_id         :integer
#  frequency      :string(255)      default("")
#  execution_time :text(65535)
#

class Event < ApplicationRecord

	serialize :execution_time, Array

	has_many :event_results, dependent: :destroy

	validates :name, :job_name, :job_arguments, :presence => true
	validates :name, :job_name, length: { in: 6..20 }
	validates :start_at, with: :start_at_is_not_past_time

	def start_at_is_not_past_time
		if self.start_at > DateTime.now
			true
		else
			errors.add(:start_date, "date should be in the future.")
			false
		end
	end	

	def self.start_job command
	 	system command
	end	
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :set_event, only: [:show, :edit, :update, :destroy, :start, :stop]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, success: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    #@event.status = "Pending"

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, success: 'Event was successfully rescheduled.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy    
    @event.destroy    
    respond_to do |format|
      format.html { redirect_to events_url, success: 'Event was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def start    
    if @event.start_at > DateTime.now
      if @event.occurrence.eql?("Once")
        create_event_results(@event, @event.start_at)        
      else
        @event.execution_time.each do |time|
          if !time.eql?("")
            @time = @event.start_at + get_execution_time(time, @event.frequency)
            create_event_results(@event, @time)            
          end
        end        
      end      
      

      flash[:success] = "Event Scheduled."
    else
      flash[:alert] = "Start At time is passed, please reshedule for future time."
    end
    redirect_to("/")
  end

  def stop
    @event_results = @event.event_results.where(:job_id => @event.job_id).limit(1)

    unless @event_results.nil? and @event_results.status.eql?("Processed")
      @job = Delayed::Job.find(@event.job_id)
      @job.delete
      @event_results.update_attributes(status: "Pending")

      flash[:success] = "Event removed from queue."
    else
      flash[:alert] = "Event has already been processed, can't be removed."
    end
    redirect_to("/")
  end

  private

    def create_event_results(event, time)      
      @job = Delayed::Job.enqueue EventJob.new(event), :run_at => time
      event.update_attributes(job_id: @job.id)
      @event_results = event.event_results.where(:job_id => event.job_id).limit(1)

      if @event_results.blank?
        event.event_results.create(job_id: event.job_id, queue: @job.queue, 
          priority: @job.priority, run_at: @job.run_at, attempts: @job.attempts, status: "Enqueued")
      else
        @event_results.update_attributes(priority: event.priority, run_at: event.start_at, status: "Enqueued")     
      end            
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :occurrence, :job_name, :job_arguments, :start_at,
                                    :priority, :frequency, :execution_time => [])
    end
end

app/helpers/events_helper.rb
module EventsHelper
	def get_event_status_class(status)
		case status
		when "Pending"
			"warning"
		when "Enqueued"
			"primary"
		when "Success"
			"success"
		when "Error"
			"danger"
		when "Failure"
			"danger"
		when "Scheduled"
			"info"
		end
	end

	def get_execution_time(time, frequency)
		case frequency
		when "minute-wise"
			time.to_i.minutes
		when "hour-wise"
			time.to_i.hours
		when "day-wise"
			time.to_i.days
		when "week-wise"
			time.to_i.weeks
		when "month-wise"
			time.to_i.months
		when "year-wise"
			time.to_i.years
		end
	end
end

app/views/events/_form.html.erb
<%= form_for(event, :html => {:class => "form-horizontal well"}) do |f| %>
  <fieldset>
    <legend>Schedule an Event</legend>
  </fieldset>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
      <%= f.text_field :name, class: "form-control" %>
    </div>  
  </div>

  <div class="form-group">
    <%= f.label :priority, class: "col-lg-2 control-label" %>
    <div class="col-lg-2">
      <%= f.select :priority, 0..10, {:selected => 10}, class: "form-control" %>
    </div>  
  </div>


  <div class="form-group">
    <%= f.label :occurrence, class: "col-lg-2 control-label" %>
    <div class="col-lg-2">
      <%= f.select :occurrence, [['Single',"Once"],['Reccurring','reccurring']], {}, class: "form-control" %>
    </div>  
  </div>

  <div class="form-group">
    <%= f.label :start_at, class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.datetime_select :start_at, {:order => [:day, :month, :year], min: Time.now}, class: "time-select" %>
    </div>  
  </div>


  <div class="form-group" id="reccurring-select">
    <%= f.label :frequency, class: "col-lg-2 control-label" %>
    <div class="col-lg-2">
      <%= f.select :frequency, [['Every Minute',"minute-wise"],['Every Hour','hour-wise'],["Every Day","day-wise"],
      ["Every Week","week-wise"], ["Every Month","month-wise"], ["Every Year","year-wise"]], {}, class: "form-control", id: "frequency-reccurring-select" %>
    </div>
    <div class="col-lg-2">
      <%= f.select :execution_time, 0...60, { }, :multiple => true, :size => 5, class: "form-control", id: "frequency-reccurring-options" %>
    </div>
  </div>


  <div class="form-group">
    <%= f.label :job_name, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
      <%= f.text_field :job_name, class: "form-control" %>
    </div>  
  </div>

  <div class="form-group">
    <%= f.label :job_arguments, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
      <%= f.text_area :job_arguments, class: "form-control" %>
    </div>  
  </div>

  <div class="form-group">
    <div class="col-lg-10 col-lg-offset-2">
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <!-- <button type="reset" class="btn btn-default">Cancel</button> -->
    </div>  
  </div>
  </fieldset>
<% end %>

app/views/events/_show_buttons.html.erb
<% if (@event.event_results.map { |er| er.status } | ["Pending"]).any? %>
  <%= link_to 'Reschedule', edit_event_path(@event), class: "btn btn-warning btn-sm pull-right" %>  
<% elsif (@event.event_results.map { |er| er.status } | ["Scheduled"]).any? %>
  <%= link_to "Enqueue", start_event_path(@event), class: "btn btn-info btn-sm pull-right" %>
  <%= link_to 'Reschedule', edit_event_path(@event), class: "btn btn-warning btn-sm pull-right" %>  
<% elsif  (@event.event_results.map { |er| er.status } | ["Enqueued"]).any? %>

<% elsif  (@event.event_results.map { |er| er.status } | ["Processing"]).any? %>
  
<% elsif  (@event.event_results.map { |er| er.status } | ["Success"]).any? %>
  <%= link_to 'Reschedule', edit_event_path(@event), class: "btn btn-warning btn-sm pull-right" %>  
<% end %>
 
<%= link_to 'Event List', events_path, class: "btn btn-primary btn-sm pull-right" %>

app/views/events/edit.html.erb
<%= render 'form', event: @event %>

<%= link_to 'Event List', events_path, class: "btn btn-primary btn-sm" %>

app/views/events/index.html.erb
<h1>Events</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
    <th>#</th>
      <th>Name</th>
      <th>Occurrence</th>
      <th>Frequency</th>
      <th>Scheduled At</th>      
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each_with_index do |event, index| %>      
    <tr class="active">
      <td><%= index + 1 %></td>
      <td><%= event.name %></td>
      <td><%= event.occurrence %></td>
      <% if event.occurrence.eql?("reccurring") %>
        <td><%= event.frequency %></td>
      <% else %>          
        <td>1</td>
      <% end %>      
      <td> <%= event.start_at > Time.now ? "will happen in" : "already happened in" %> <%= time_ago_in_words(event.start_at) %> </td>
      
      <% if (event.event_results.map { |er| er.status } & ["Processing","Enqueued"]).any? %>
        <td><%= link_to "Stop", stop_event_path(event), class: "btn btn-danger btn-xs" %></td>
        <td><%= link_to 'Logs', event, class: "btn btn-info btn-xs" %></td>
      <% else %>
        <td><%= link_to "Enqueue", start_event_path(event), class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Logs', event, class: "btn btn-info btn-xs" %></td>
        <td><%= link_to 'Reschedule', edit_event_path(event), class: "btn btn-warning btn-xs" %></td>
        <td><%= link_to 'Remove', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"%></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New Event', new_event_path, class: "btn btn-primary btn-sm" %>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

<%= link_to 'Event List', events_path, class: "btn btn-primary btn-sm" %>

app/views/events/show.html.erb
<%= render "show_buttons" %>

<blockquote>
  <p>
    <p>
      <strong>Name:</strong>
      <%= @event.name %>
    </p>

    <p>
      <strong>Occurrence:</strong>
      <%= @event.occurrence.camelize %>
    </p>
    <p>
      <strong>Frequency:</strong>
      <%= @event.frequency.camelize %>
    </p>
    
    <p>
      <strong>Scheduled At:</strong>
      <%= @event.start_at.strftime("%d-%B-%Y - %a - %I:%M %p") %>
    </p>
    <% if @event.occurrence.eql?("reccurring") %>
    <p>
      <strong>Execution Scheduled At:</strong><br>      
      <% @event.event_results.each do |er| %>
        <%= er.run_at.strftime("%d-%B-%Y - %a - %I:%M %p") %><br>
      <% end %>
    </p>
    <% end %>
    <p>
      <strong>Job name:</strong>
      <%= @event.job_name %>
    </p>

    <p>
      <strong>Job arguments:</strong>
      <%= @event.job_arguments %>
    </p>

  </p>
  <small>SubEvents:</small>    
      <table class="table table-striped table-hover">
          <thead>
            <tr>
            <th>#</th>
              <th>In Queue</th>
              <th>Scheduled Time</th>
              <th>Status</th>      
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>  
      <% @event.event_results.each_with_index do |er, index| %>
        <tr class="active">
          <td><%= index + 1 %></td>
          <td><%= er.queue %></td>              
          <td> <%= er.run_at > Time.now ? "will happen in" : "happened in" %> <%= time_ago_in_words(er.run_at) %> </td>
          <td><span class="label label-<%= get_event_status_class(er.status) %>"><%= er.status %></span></td>
          <% if er.status.eql?("Processing") or er.status.eql?("Enqueued") %>
            <td><%= link_to "Stop", stop_event_result_path(er), class: "btn btn-danger btn-xs" %></td>
          <% else %>
            <% if er.status.eql?("Scheduled") %>
              <td><%= link_to "Enqueue", start_event_result_path(er), class: "btn btn-primary btn-xs" %></td>
            <% else %>  
              <td><%= link_to 'Reschedule', edit_event_result_path(er), class: "btn btn-warning btn-xs" %></td>
            <% end %>            
            <td><%= link_to 'Remove', er, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"%></td>
          <% end %>
        </tr>
        <% unless er.last_error.blank? %>
          <%= er.last_error %><br>
          Occured at : <%= er.failed_at %> 
        <% end %>  
    <% end %>  
    </tbody>
  </table>
</blockquote>

<%= render "show_buttons" %>