config/routes.rb
Rails.application.routes.draw do

  resources :events do
  	member do
  		get 'start'
  		get 'stop'
  	end
  end
  resources :event_results, :only => [:edit, :update, :destroy] do
  	member do
  		get "start"
  		get "stop"
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "events#index"
end

app/models/event_result.rb
# == Schema Information
#
# Table name: event_results
#
#  id         :integer          not null, primary key
#  event_id   :integer
#  job_id     :string(255)
#  queue      :string(255)
#  attempts   :integer
#  last_error :text(65535)
#  priority   :integer
#  locked_by  :text(65535)
#  run_at     :datetime
#  failed_at  :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :string(255)      default("Pending")
#

class EventResult < ApplicationRecord
	belongs_to :event

	validates :run_at, with: :run_at_is_not_past_time

	def run_at_is_not_past_time
		if self.run_at > DateTime.now
			true
		else
			errors.add(:run_at, "date should be in the future.")
			false
		end
	end	

end

app/controllers/event_results_controller.rb
class EventResultsController < ApplicationController
  before_action :set_event_result, only: [:edit, :update, :destroy, :stop, :start]

  # GET /event_results/1/edit
  def edit
  end

  
  # PATCH/PUT /event_results/1
  # PATCH/PUT /event_results/1.json
  def update
    @event_result.status = "Scheduled"
    respond_to do |format|
      if @event_result.update(event_result_params)
        format.html { redirect_to @event_result.event, success: 'Sub Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_result }
      else
        format.html { render :edit }
        format.json { render json: @event_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_results/1
  # DELETE /event_results/1.json
  def destroy
    @event_result.destroy
    respond_to do |format|
      format.html { redirect_to event_path(@event_result.event), success: 'Sub Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def start    
    if @event_result.run_at > DateTime.now
      begin
        @job = Delayed::Job.find(@event_result.job_id)
        unless @job.nil?          
          @job.invoke_job
        end
      rescue ActiveRecord::RecordNotFound
        
      end
      @job = Delayed::Job.enqueue EventJob.new(@event_result.event), :run_at => @event_result.run_at
      @event_result.status = "Enqueued"
      @event_result.job_id = @job.id
      @event_result.save(:validate => false)
      
      flash[:success] = "Event Scheduled."
    else
      flash[:alert] = "Run At time is passed, please reshedule for future time."
    end
    redirect_to event_path(@event_result.event)
  end

  def stop
    unless @event_result.nil? and @event_result.status.eql?("Processed")
      begin 
        @job = Delayed::Job.find(@event_result.job_id)
        unless @job.nil?
          @job.delete
        end
      rescue ActiveRecord::RecordNotFound
        
      end      
      @event_result.status = "Pending"
      @event_result.job_id = ""
      @event_result.save(:validate => false)

      flash[:success] = "Sub Event removed from queue."
    else
      flash[:alert] = "Sub Event has already been processed, can't be removed."
    end
    redirect_to event_path(@event_result.event)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_result
      @event_result = EventResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_result_params
      params.require(:event_result).permit(:run_at, :priority, :attempts, :last_error, :failed_at,
                                         :status, :event_id, :job_id, :queue)
    end
end

app/helpers/event_results_helper.rb
module EventResultsHelper
end

app/views/event_results/_form.html.erb
<%= form_for(event_result, :html => {:class => "form-horizontal well"}) do |f| %>
  <fieldset>
    <legend>Schedule SubEvent</legend>
  </fieldset>
  <% if event_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_result.errors.count, "error") %> prohibited this Sub event from being saved:</h2>

      <ul>
      <% event_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :priority, class: "col-lg-2 control-label" %>
    <div class="col-lg-2">
      <%= f.select :priority, 0..10, {:selected => 10}, class: "form-control" %>
    </div>  
  </div>

  <div class="form-group">
    <%= f.label :run_at, class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.datetime_select :run_at, {:order => [:day, :month, :year], min: Time.now}, class: "time-select" %>
    </div>  
  </div>

  <div class="form-group">
    <%#= f.label :job_arguments, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
      <%#= f.text_area :job_arguments, class: "form-control" %>
    </div>  
  </div>

  <div class="form-group">
    <div class="col-lg-10 col-lg-offset-2">
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <!-- <button type="reset" class="btn btn-default">Cancel</button> -->
    </div>  
  </div>
  </fieldset>
<% end %>

app/views/event_results/edit.html.erb
<%= render 'form', event_result: @event_result %>

<%= link_to 'Return to Main Event', @event_result.event, class: "btn btn-primary btn-sm" %> 

<%#= link_to 'Back', event_results_path %>